import argparse
import glob
import json
import os


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--gen_dataset_path", type=str, required=True,
                        help="Directory containing gen_data_*.json files")
    parser.add_argument("--output_path", type=str, default=None,
                        help="Path for the submission JSON. Defaults to <gen_dataset_path>/activitynet_dvc_pred.json")
    return parser.parse_args()


def main(args):
    gen_data_paths = sorted(glob.glob(os.path.join(args.gen_dataset_path, "gen_data_*.json")))
    if not gen_data_paths:
        raise FileNotFoundError(f"No gen_data_*.json files found in {args.gen_dataset_path}")
    print(f"Loading from: {gen_data_paths}")

    gen_data = []
    for path in gen_data_paths:
        with open(path, "r", encoding="utf-8") as f:
            gen_data.extend(json.load(f))
    print(f"Total predicted segments: {len(gen_data)}")

    results = {}
    for item in gen_data:
        video_id = item["qid"]  # set to video_id (e.g. "v_uqiMw7tQ1Cc") by load_activitynet_dvc_eval
        if video_id not in results:
            results[video_id] = []
        results[video_id].append({
            "timestamp": item["timestamp"],
            "sentence": item["sentence"],
        })

    for video_id in results:
        results[video_id].sort(key=lambda x: x["timestamp"][0])

    submission = {
        "results": results,
        "version": "VERSION_1.0",
        "external_data": {"used": False, "description": "Generated by model"},
    }

    output_path = args.output_path or os.path.join(args.gen_dataset_path, "activitynet_dvc_pred.json")
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(submission, f, indent=4, ensure_ascii=False)

    print(f"Saved submission for {len(results)} videos to {output_path}")


if __name__ == "__main__":
    main(get_args())
